### ISSUE TITLE
test_gpio gpio_set_bias(gpio, GPIO_BIAS_PULL_UP) fails

### ISSUE THREAD

**Issue by pezi** [vsergeev/c-periphery#41] opened 2021-04-19 05:27 UTC
On a RPi 3B+ with Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

``` cli
 ./test_gpio /dev/gpiochip0 17 27
[ OK ]  /home/pi/c-periphery/tests/test_gpio.c test_open_config_close():151  edge == GPIO_EDGE_NONE
 [FAIL]  /home/pi/c-periphery/tests/test_gpio.c test_open_config_close():154  gpio_set_bias(gpio, GPIO_BIAS_PULL_UP) == 0
```

Fails also for su, not cable connection at this point of the test. 
Any idea?

**Comment by vsergeev** [comment] 2023-03-31 10:25
I'm unable to reproduce the failure -- I just ran the test successfully on a RPi 3B+. It might be worth trying a newer kernel.

Closing for now, but feel free to re-open if you believe it's an issue with c-periphery.

**Closed by vsergeev** 2023-03-31 10:25 UTC
